web:
  build: .
  volumes:
    - ./package.json:/opt/package.json
    - ./lib/:/opt/lib/
    - ./run.sh:/opt/run.sh
  ports:
    - "3000:3000"
  environment:
    MANDATORY_HEADER: X-Foo
    MANDATORY_HEADER_VALUE: xxx
